### ISSUE TITLE
react 元件架構圖

### ISSUE THREAD

**Issue by andrewchen30** [PolarBearAndrew/CodePioneer#10]
#### 針對每個元件做說明

**_資料先做一比就好，大家確定後再繼續**_
- 每個元件需要整理這些資料
- 再問問 @keami326  怎麼處理排版
- [ ] 功能 ( 盡量撰寫約 100 - 200 字的敘述 )
- [ ] 引用套件
- [ ] 父節點名稱
- [ ] 子節點名稱 ( 可能多個 )
- [ ] hook... ( 這個先保留不做 )

**Comment by Dobubu** [comment]
我寫好一個範例了，是直接貼在這邊麼？還是上傳雲端 or FB

**Comment by andrewchen30** [comment]
禮拜二討論就好
你獨立開一個新的 `.docx` 來寫

**Comment by Dobubu** [comment]
好喔
這是範例連結 https://drive.google.com/open?id=1PxHRiOuOrYD3NnttE6n_DV_ZfJGlE5wNeMJBl1y9Eaw

**Comment by andrewchen30** [comment]
### login
- 父節點：main
- 子節點：無

可以點擊「SIGNUP」來做註冊的動作，依序輸入相關資料，再點擊「SURE」即可完成註冊。登入方面：使用者輸入信箱及密碼，點擊「LOGIN」若有成功登入即直接進入網站主頁；若信箱和密碼有錯誤，會在左下方出現提醒訊息，再重新輸入一次。取回密碼方面：當您忘記您的密碼時，可點擊「FORGET PASSWORD」，輸入您的信箱資料，再點擊「SUBMIT」，系統將會送出信件，讓您可以取回密碼。

#### 元件簡述
1. 登入驗證
2. 註冊功能
3. 密碼取回
4. 

#### 相依元件
1. material-ui.Dialog
2. material-ui.Snackbar
3. material-ui.TextField
4. material-ui.FlatButton
5. material-ui.RaisedButton

#### 相依套件
1. react

#### Hook Actions
1. AppActions_User.login
2. AppActions_User.singUp
3. AppActions_User.forgetPwd

**Comment by Dobubu** [comment]
main 和 container 功能說明還沒寫
這邊是連結：https://drive.google.com/open?id=0B7CxSvWOJa4-eVU5LWRlb2hvX2M

**Comment by Dobubu** [comment]
@PolarBearAndrew  main就麻煩你寫了，其他我寫好了你再檢查看看
這邊是連結：https://drive.google.com/open?id=1KXOdxUDqEaSZ8tEhVeOGPCrjj74FP02aPLvvB_WRkTA (檔案在「專題」資料夾最外面)

note :  這個才是對的
