### ISSUE TITLE
SD

### ISSUE THREAD

**Issue by andrewchen30** [PolarBearAndrew/CodePioneer#11]
- [x] 前面的系統設計圖
  整理整理即可

**Comment by PolarBearAndrew** [comment]
刪選系統展示圖 是否有高度重複的

**Comment by keami326** [comment]
整理的意思是??

**Comment by andrewchen30** [comment]
排一排拉到後面當作附件就好了
這個工作原有有要處有要處其他東西
後來被我移除掉了
你的重點是 #18

**Comment by keami326** [comment]
我如果改word檔的話，然後你也再改文獻探討的參考文獻引用，這樣檔案就會有兩個了
還是到時候再把大家改的word做統整?

**Comment by andrewchen30** [comment]
有道理 
沒問題
