### ISSUE TITLE
海報

### ISSUE THREAD

**Issue by andrewchen30** [PolarBearAndrew/CodePioneer#13]
- [ ] 系上專用的底稿(?
- [ ] 標題
- [ ] logo
- [ ] 文案
- [ ] 組員
- [ ] 老師
- [ ] 放個圖表或圖上去(討論要放什麼)

**Comment by andrewchen30** [comment]
我記得有兩種檔案都要

**Comment by Dobubu** [comment]
系上說，全部自己來，沒有格式限制。
