### ISSUE TITLE
影片規劃

### ISSUE THREAD

**Issue by andrewchen30** [PolarBearAndrew/CodePioneer#14]
- 十分鐘
- 規劃一下 10 分鐘大概要講什麼資料
- 在下面撰寫規劃就好了
##### 條列式撰寫 demo

```
* 項目1
* 項目2
* 項目3
```

**Comment by andrewchen30** [comment]
跟 @keami326  重複確認內容喔，或許有什麼特別的東西是必要的內容?

**Comment by andrewchen30** [comment]
這應該還會有其他工作出現，所以先整理有哪些要做，然後我在統一分工

**Comment by q3856245** [comment]
- 主題介紹
- 演算法部分
- 系統操作

**Comment by andrewchen30** [comment]
already done
