### ISSUE TITLE
其他資料-操作手冊(評估)

### ISSUE THREAD

**Issue by andrewchen30** [PolarBearAndrew/CodePioneer#18]

**Comment by andrewchen30** [comment]
我想知道我們把之前的系統截圖改成操作手冊的可能性
有沒有什麼規範
嚴格來說我們的操作手冊不難寫
(畢竟畫面不多)

**Comment by keami326** [comment]
像一個完全沒看過這個系統的使用者，來操作的話，要寫出他能看得懂如何操作此系統的操作手冊。
系統的功能依照步驟一個一個寫出來，可以像是
步驟一 輸入帳號密碼...以此類推，如果有例外像是忘記密碼，可能就寫在步驟一裡"例外狀況"這樣，
那RWD這個功能就放到步驟都寫完再寫好了，應該是這樣啦

**Comment by keami326** [comment]
1.寄送每日郵報應該可以再使用手冊裡寫一下，告訴使用者每日會寄送郵報
2.SourceTree 實際使用情況，這個應該就不用放進使用手冊了吧?

**Comment by andrewchen30** [comment]
Source Tree 跟系統無關，應該就不用放進去了
所以我們需要的使用手冊內容有：
1. 註冊
2. 登入 ( ? )
3. 取回密碼
4. 每日郵報
5. 追蹤領頭羊
6. 收藏喜愛的文章
7. 查看自己的收藏
8. 設定

還有需要增補的或刪除的嗎?
@Dobubu  @keami326 

P.S. 璇話說你這樣打就可以打條列式，他會自動幫你編號

```
1. 項目一
1. 項目二
1. 項目三
```

##### 注意點點跟文字中簽有個空白

**Comment by Dobubu** [comment]
我剛剛有一個一個看畫面對照，該有的都有了。
對了，那我們沒做搜尋這個功能，需要把左側欄最下面的搜尋功能拿掉麼？

**Comment by andrewchen30** [comment]
不用拿掉了 反正老師也沒在看
老師說的話 我們就把它寫進未來展望裡面
