### ISSUE TITLE
其他資料-Source Code 壓縮與整理

### ISSUE THREAD

**Issue by andrewchen30** [PolarBearAndrew/CodePioneer#19]
- [x] 刪掉不必要的資料
- [x] 確認專題還能跑
- [x] DB 不用給他一份，因為我們的 auto build

**Comment by q3856245** [comment]
刪掉不必要的資料例如像是?

**Comment by andrewchen30** [comment]
1. 先把整個 CodePioneer 複製出來，不要在 Git 裡面刪除
2. 把爬蟲的資料複製一份下來 ( 估計以後真的有人用的話，爬蟲也壞了 )
3. 刪掉不必要的資料：簡報等等，有很多都儲存在 Github 裡面
4. 壓縮整個 source code 的時候，node_module 不要進去

目前只想到這樣XD
