### ISSUE TITLE
系統開發與技術

### ISSUE THREAD

**Issue by andrewchen30** [PolarBearAndrew/CodePioneer#5]
- [ ] 補系統架構圖

**Comment by q3856245** [comment]
補系統架構圖是哪一張?

**Comment by andrewchen30** [comment]
<img width="702" alt="2015-12-26 10 38 04" src="https://cloud.githubusercontent.com/assets/8358609/12004924/caf6f710-abbc-11e5-97f0-350aaad4df0e.png">

其實就是這張
有幾個點要修改
- MobileApp 那邊要拿掉，只留 WebApp
- 那四個爬蟲的網站要弄一下 好看一點，然後也要以線連過去
- Node.js 跟 React 的圖都有點醜，要重弄 ( 我們資料裡面應該已經有比較好的了 )
- calculate server 整個拿掉，現在沒有這種東西

P.S. 好看的 React 和 Node Icon 請參考文件中的 `4.7.1 原生 flux 流程圖`

**Comment by q3856245** [comment]
需要原黨改圖

**Comment by andrewchen30** [comment]
弄新的 :"D

**Comment by q3856245** [comment]
https://drive.google.com/open?id=0B-MKhafsxG72QlBYcW4yZlVTQUE
