### ISSUE TITLE
SA-環境圖與資料流程圖

### ISSUE THREAD

**Issue by andrewchen30** [PolarBearAndrew/CodePioneer#7]
# 重做環境圖就好
- [ ] 環境圖要重新製作
- [x] 將後面的 react.js flux 那部份的資料拉到前面來，做成資料流程圖

**Comment by Dobubu** [comment]
我看不懂第二點耶

**Comment by andrewchen30** [comment]
以後 SA 的順序大概長這樣
1. 環境圖
2. React.js 元件架構圖
3. 元件架構圖解說 
4. Flux 資料流程圖
5. Flux 實作圖 ( 小張 )
6. Flux 實作圖 ( 超大那張 )
7. API 文件

**Comment by Dobubu** [comment]
恩 那第二點，「將後面的 react.js flux 那部份的資料拉到前面來，做成資料流程圖」，是只要改順序，還是要重做?

**Comment by Dobubu** [comment]
所以第二點的意思，是換順序就好了 ?

**Comment by andrewchen30** [comment]
要整理 
如果覺得缺少哪些文章跟我說

**Comment by andrewchen30** [comment]
ok 了
